name: MusicHubTR Otomatik Yayin
on:
  schedule:
    - cron: '0 6 * * *'
    - cron: '0 7 * * *'
  workflow_dispatch:
jobs:
  topla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo topla
  yayinla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo 10:00 yayinla
